remove optimizationResults and use optimizationVectorPostprocessor
zachmprince/isopod pull request #3
Opened 2020-10-17 00:35 UTC by lynnmunday

This removes the original optimization vector postprocessor Zach put in and replaces it with one that will be easier to use for transfers.

2020-10-19 16:40 UTC, dewenyushu requested changes

2020-10-19 16:40 UTC, dewenyushu commented on test/tests/multiapps/optimiation_transfer/master.i
>    type = QuadraticMinimize
I am confused here. In this input we are solving the force inversion for the diffusion problem, right? It seems to be the case according to the later input blocks. Then we should have a different form function here. A new class is needed, where the objective function and the gradient (and the hessian) will be defined correspondingly.

2020-10-19 16:40 UTC, dewenyushu commented on include/formfunctions/FormFunction.h
> +  dof_id_type _ndof;
Why we should not keep the number of parameters as `const`? Are we changing the number of parameters later?

2020-10-19 16:40 UTC, dewenyushu commented on include/formfunctions/FormFunction.h
> -
I think it makes sense to keep this `_initial_condition` here. Would you mind explaining why you delete this?

2020-10-19 17:58 UTC, lynnmunday commented on test/tests/multiapps/optimiation_transfer/master.i
>    type = QuadraticMinimize
This PR is only for replacing Zach's postprocessor with a slightly different one.  I will add another commit to do gradient from optimization with a new form function for diffusion.

2020-10-19 18:00 UTC, lynnmunday commented on include/formfunctions/FormFunction.h
> +  dof_id_type _ndof;
I can no longer set this in the constructor initialization list.  I'm no longer filling a vector during intitialization whose size was used to set ndof

2020-10-19 18:00 UTC, lynnmunday commented on include/formfunctions/FormFunction.h
> -
I moved initial condition to the optimization vector post-processor.  We could keep it in this class but it is going to be set in the vpp.

2020-10-20 14:26 UTC, dewenyushu commented on include/formfunctions/FormFunction.h
> -
Oh okay I see. I felt it would make more sense mathematically to have initial values in the form function. But putting it in the vpp seems to be more convenient in terms of implementation.

2020-10-20 14:26 UTC, dewenyushu approved these changes

2020-10-20 23:20 UTC, merged